baseURL: https://karimmfa2022.netlify.app/
languageCode: en-us
title: Karim El Asmar
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Welcome to my website!
    title: Hi, my name is Karim
  blog: {}
  contact:
    address:
      - title: Address
        street: London Business School, Regent's Park
        city: London, NW1 4SA
        country: United Kingdom
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kelasmar.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Content and pictures by Karim El Asmar 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/karim.asmar.54/
      - icon: fa-github
        label: GitHub
        url: https://github.com/kelasmar
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/karim-el-asmar/
  image: ''
  name: Karim El Asmar
  navigation:
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/me
      - name: R x Python 
        url: blogs2
    title: Karim El Asmar's portfolio
  tiles:
    enable: yes
    showcase:
      - image: mypic.jpg
        subtitle: Biography
        title: About me
        url: blogs/me
      - image: CoffeeChat.jpg
        subtitle: Download my CV
        title: My CV
        url: blogs/myCV.pdf
      - image: LBS.jpg
        subtitle: Website of LBS
        title: London Business School
        url: https://www.london.edu/
      - image: CS.jpg
        subtitle: Website of CentraleSupélec
        title: CentraleSupélec
        url: https://www.centralesupelec.fr/en/
      - image: ETH.jpg
        subtitle: Valuation
        title: Ethereum
        url: blogs/EthereumValuation
      - image: Bitcoin.jpg
        subtitle: Price Analysis
        title: Bitcoin
        url: blogs/Bitcoin.pdf
      - image: CBDC.jpg
        subtitle: CBDC
        title: Centrale Bank Digital Currency
        url: blogs/CBDC
      - image: Monetary.jpg
        subtitle: Analysis of the Lebanon's Economic Collapse
        title: Monetary System
        url: blogs/MS.pdf
      - image: Financial Markets.jpg
        subtitle: Portfolio Optimization
        title: Financial Market
        url: blogs/FM.pdf
      - image: Virus.jpg
        subtitle: Modelization project
        title: Virus Propagation
        url: blogs/Virus.pdf
  two:
    enable: yes
    subtitle: "In this section you will find other R and Python projects"
    title: R x Python
    url: blogs2
    buttonText: Take a look at my projects!
