baseURL: http://example.org/
languageCode: en-us
title: Karim El Asmar
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Welcome to my website!
    title: Hi, my name is Karim
  blog: {}
  contact:
    address:
      - city: Regent's Park, London NW1 4SA
        country: United Kingdom
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kelasmar.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7463-443-490
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/karim.asmar.54/
      - icon: fa-github
        label: GitHub
        url: https://github.com/kelasmar
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/karim-el-asmar/
  image: ''
  name: Karim El Asmar
  navigation:
    links:
      - name: Home
        url: '#'
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Biography
        title: About me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Download my CV
        title: my CV
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Website of LBS
        title: London Business School
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Website of CentraleSupélec
        title: CentraleSupéllec
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
